### ISSUE TITLE
Correction while running the algorithm

### ISSUE THREAD

**Issue by deadshotsb** [goenkamanik/SearchAlgoVisualizer#1]
This is a good idea for an initial start, but I personally think addition of these few ideas may help:-

* You might consider disabling the **Generate new array** option while running a particular algorithm, as while running a particular algorithm on a generated sequence. If the option is chosen to generate another sequence while running an algorithm, then your algorithm extends for the newly generated sequence but with the previously generated search parameters.

* When comparing between search algorithms you may consider adding interpolation and extrapolation search and comparing all the search results for a better understanding.

**Comment by goenkamanik** [comment]
Thanks for your feedback. I'll consider the mentioned additions/changes.
